has.app/has.app/Controllers/ChartController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using has.app.Components;
using has.app.Models;
using Microsoft.AspNet.SignalR;
using MongoDB.Bson;
using MongoDB.Driver;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using uPLibrary.Networking.M2Mqtt.Messages;


namespace has.app.Controllers
{
    public class ChartController : Controller
    {
        public ActionResult GenerateData()
        {
            return View();
        }
        public ActionResult GenerateDummyData(paramGenerate atr)
        {
            Dictionary<string, string> ResultData = new Dictionary<string, string>();
            Dictionary<int, int> dictionary = new Dictionary<int,int> { { 1, 31 }, { 2, 28 }, { 3, 31 }, { 4, 30 }, { 5, 31 }, { 6, 30 }, { 7, 31 }, { 8, 31 }, { 9, 30 }, { 10, 31 }, { 11, 30 }, { 12, 31 } };

            var database = Constants.client.GetDatabase("IoT");
            var DataLogs = database.GetCollection<BacnetNew_REC>(atr.collection);

            for (int m = atr.StartM; m <= atr.EndM; m++)
            {
                int dl = dictionary[m];
                if (m == 8) { dl = 23; }
                for (int d = 1; d <= dl; d++)
                {
                    for (int h = 8; h <= 19; h++)
                    {
                        BacnetNew_REC voBacnet = new BacnetNew_REC();
                        string iString = "2019-" + m.ToString("D2") + "-" + d.ToString("D2") + " "+ h.ToString("D2") + ":00:02";
                        DateTime oDate = DateTime.ParseExact(iString, "yyyy-MM-dd HH:mm:ss", System.Globalization.CultureInfo.InvariantCulture);

                        Random random = new Random();
                        int PresentValue = random.Next(atr.Min, atr.Max);
                        if (oDate.ToString("dddd") == "Sunday" || oDate.ToString("dddd") == "Saturday") {
                            PresentValue = random.Next(atr.Min, atr.Max) * 30 / 100;
                        }

                        voBacnet.RecordTimestamp = oDate;
                        voBacnet.DeviceID = atr.DeviceID;
                        voBacnet.DeviceName = atr.DeviceName;
                        voBacnet.ObjectName = atr.objName;
                        voBacnet.PresentValue = PresentValue;
                        voBacnet.InstanceID = atr.Instance;
                        voBacnet.Units = "Kwh";

                        DataLogs.InsertOne(voBacnet);
                        Thread.Sleep(100);
                    }
                }
            }

            ResultData.Add("msg", "Success");
            ResultData.Add("errorcode", "0");
            ResultData.Add("title", "Success");
            return Json(ResultData, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ConsDeviceHome()
        {
            var database = Constants.client.GetDatabase("IoT");
            var Aircond = database.GetCollection<DPC_Chart_REC>("AircondDataLogs");
            var Lighting = database.GetCollection<DPC_Chart_REC>("LightingDataLogs");
            var Elevator = database.GetCollection<DPC_Chart_REC>("ElevatorDataLogs");
            var Plugload = database.GetCollection<DPC_Chart_REC>("PlugloadDataLogs");

            var pipline = "{ $group: { _id: { day: { $dayOfMonth: \"$RecordTimestamp\"}, month: { $month: \"$RecordTimestamp\"}, year: { $year: \"$RecordTimestamp\" } },  Current: { $sum: \"$PresentValue\" }} }";
            var BuilderA = Aircond.Aggregate().AppendStage<DPC_Chart_REC>(pipline);
            var BuilderL = Lighting.Aggregate().AppendStage<DPC_Chart_REC>(pipline);
            var BuilderE = Elevator.Aggregate().AppendStage<DPC_Chart_REC>(pipline);
            var BuilderP = Plugload.Aggregate().AppendStage<DPC_Chart_REC>(pipline);
            Dictionary<string, List<DPC_Chart_REC>> Result = new Dictionary<string, List<DPC_Chart_REC>>();
            List<DPC_Chart_REC> Devices = new List<DPC_Chart_REC>();
            var resA = BuilderA.ToList().Where(w => w.DateTime >= DateTime.Now).OrderBy(o => o.Day);
            var resL = BuilderL.ToList().Where(w => w.DateTime >= DateTime.Now).OrderBy(o => o.Day);
            var resE = BuilderE.ToList().Where(w => w.DateTime >= DateTime.Now).OrderBy(o => o.Day);
            var resP = BuilderP.ToList().Where(w => w.DateTime >= DateTime.Now).OrderBy(o => o.Day);

            if (resA.Count() > 0)
            {
                Devices.AddRange(resA);
                Result.Add("AirCond", Devices);
            }
            else
            {
                DPC_Chart_REC nullD = new DPC_Chart_REC();
                nullD.Current = 0;
                Devices.Add(nullD);
                Result.Add("AirCond", Devices);
            }
            if (resA.Count() > 0)
            {
                Devices = new List<DPC_Chart_REC>();
                Devices.AddRange(resL);
                Result.Add("Lighting", Devices);
            }
            else
            {
                DPC_Chart_REC nullD = new DPC_Chart_REC();
                nullD.Current = 0;
                Devices.Add(nullD);
                Result.Add("Lighting", Devices);
            }
            if (resA.Count() > 0)
            {
                Devices = new List<DPC_Chart_REC>();
                Devices.AddRange(resE);
                Result.Add("Elevator", Devices);
            }
            else
            {
                DPC_Chart_REC nullD = new DPC_Chart_REC();
                nullD.Current = 0;
                Devices.Add(nullD);
                Result.Add("Elevator", Devices);
            }
            if (resA.Count() > 0)
            {
                Devices = new List<DPC_Chart_REC>();
                Devices.AddRange(resP);
                Result.Add("Plugload", Devices);
            }
            else
            {
                DPC_Chart_REC nullD = new DPC_Chart_REC();
                nullD.Current = 0;
                Devices.Add(nullD);
                Result.Add("Plugload", Devices);
            }

            return Json(Result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult DayliPowerConsumtion()
        {
            var database = Constants.client.GetDatabase("IoT");
            var Aircond = database.GetCollection<DPC_Chart_REC>("AircondDataLogs");
            var Lighting = database.GetCollection<DPC_Chart_REC>("LightingDataLogs");
            var Elevator = database.GetCollection<DPC_Chart_REC>("ElevatorDataLogs");
            var Plugload = database.GetCollection<DPC_Chart_REC>("PlugloadDataLogs");

            var pipline = "{ $group: { _id: { day: { $dayOfMonth: \"$RecordTimestamp\"}, month: { $month: \"$RecordTimestamp\"}, year: { $year: \"$RecordTimestamp\" } },  Current: { $sum: \"$PresentValue\" }} }";
            var BuilderA = Aircond.Aggregate().AppendStage<DPC_Chart_REC>(pipline);
            var BuilderL = Lighting.Aggregate().AppendStage<DPC_Chart_REC>(pipline);
            var BuilderE = Elevator.Aggregate().AppendStage<DPC_Chart_REC>(pipline);
            var BuilderP = Plugload.Aggregate().AppendStage<DPC_Chart_REC>(pipline);

            List<DPC_Chart_REC> Result = new List<DPC_Chart_REC>();
            var resA = BuilderA.ToList().Where(w => w.DateTime >= DateTime.Now.AddDays(-7)).OrderBy(o => o.Day);
            var resL = BuilderL.ToList().Where(w => w.DateTime >= DateTime.Now.AddDays(-7)).OrderBy(o => o.Day);
            var resE = BuilderE.ToList().Where(w => w.DateTime >= DateTime.Now.AddDays(-7)).OrderBy(o => o.Day);
            var resP = BuilderP.ToList().Where(w => w.DateTime >= DateTime.Now.AddDays(-7)).OrderBy(o => o.Day);
            Result.AddRange(resA);
            Result.AddRange(resL);
            Result.AddRange(resE);
            Result.AddRange(resP);

            return Json(Result.GroupBy(p => p.DayName).Select(g => new { DayName = g.Key, Current = g.Sum(s => s.Current), BaseLine = g.Sum(s => s.BaseLine) }), JsonRequestBehavior.AllowGet);
        }
        
    }
}

has.app/has.app/Views/Chart/GenerateData.cshtml
@{
    Layout = "~/Views/Shared/_NoDigitalTwin.cshtml";
}

<script src="https://cdn.jsdelivr.net/npm/gasparesganga-jquery-loading-overlay@2.1.6/dist/loadingoverlay.min.js"></script>
<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label for="DeviceID">DeviceID</label>
            <input type="text" id="DeviceID" class="form-control" style="min-width:50%;" placeholder="DeviceID" />
        </div>
        <div class="form-group">
            <label for="DeviceName">DeviceName</label>
            <input type="text" id="DeviceName" class="form-control" style="min-width:50%;" placeholder="DeviceName" />
        </div>
        <div class="form-group">
            <label for="Instance">Instance</label>
            <input type="text" id="Instance" class="form-control" style="min-width:50%;" placeholder="Instance" />
        </div>
        <div class="form-group">
            <label for="Object Name">Object Name</label>
            <input type="text" id="objName" class="form-control" style="min-width:50%;" placeholder="objName" />
        </div>
        <div class="form-group">
            <label for="Start Month">Start Month</label>
            <select class="form-control" id="StartM" style="min-width:50%;" placeholder="StartD">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
                <option value="7">7</option>
                <option value="8">8</option>
                <option value="9">9</option>
                <option value="10">10</option>
                <option value="11">11</option>
                <option value="12">12</option>
            </select>
        </div>
        <div class="form-group">
            <label for="End Month">End Month</label>
            <select id="EndM" class="form-control" style="min-width:50%;" placeholder="EndM">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
                <option value="7">7</option>
                <option value="8">8</option>
                <option value="9">9</option>
                <option value="10">10</option>
                <option value="11">11</option>
                <option value="12">12</option>
            </select>
        </div>
        <div class="form-group">
            <label for="Max">Max Value</label>
            <input type="text" id="Max" class="form-control" style="min-width:50%;" placeholder="Max" />
        </div>
        <div class="form-group">
            <label for="Min">Min Value</label>
            <input type="text" id="Min" class="form-control" style="min-width:50%;" placeholder="Max" />
        </div>
        <div class="form-group">
            <label for="Collection">Collection</label>
            <select id="collection" class="form-control" style="min-width:50%;" placeholder="collection">
                <option value="AircondDataLogs">AirCond</option>
                <option value="ElevaotDataLogs">Elevator</option>
                <option value="LightingDataLogs">Lighting</option>
                <option value="PlugloadDataLogs">Plugload</option>
            </select>
        </div>
        <button onclick="publishToBroker();">Generate</button>
    </div>
</div>
<script>
    function publishToBroker() {
        var StartD = $("#StartD").val();
        var EndD = $("#EndD").val();
        var StartM = $("#StartM").val();
        var EndM = $("#EndM").val();
        var Max = $("#Max").val();
        var Min = $("#Min").val();
        var collection = $("#collection").val();
        var objName = $("#objName").val();
        var Instance = $("#Instance").val();
        var DeviceID = $("#DeviceID").val();
        var DeviceName = $("#DeviceName").val();
        var voData = {
            StartD : StartD,
            EndD : EndD,
            StartM : StartM,
            EndM : EndM,
            Max : Max,
            Min : Min,
            collection : collection,
            objName : objName,
            Instance : Instance,
            DeviceID : DeviceID,
            DeviceName :DeviceName
        };
        $.ajax({
            type: 'POST',
            url: '@Url.Action("GenerateDummyData", "Chart")',
            data: JSON.stringify(voData),
            dataType: 'json',
            contentType: 'application/json; charset=utf-8',
            beforeSend: function () {
                $.LoadingOverlay("show", {
                    image       : "",
                    fontawesome : "fa fa-cog fa-spin"
                });
            },
            success: function (result) {
                $.LoadingOverlay("hide", {
                    image       : "",
                    fontawesome : "fa fa-cog fa-spin"
                });
                alert(result.msg);
            }
        });
    }
</script>